export { default as Home } from "./Home"
export { default as AboutUs } from "./AboutUs"
export { default as Projects } from "./Projects"
export { default as Seminars } from "./Seminars"
export { default as Album } from "./Album"
export { default as Admin } from "./Admin"
